vich_uploader:
    db_driver: orm

    mappings:
        good_image:
            uri_prefix: images/goods
            upload_destination: '%kernel.project_dir%/public/images/goods'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
