#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

sell:
  path: /sell
  controller: App\Controller\GoodController::sell

good:
  path: /good/{good_id}
  controller: App\Controller\GoodController::good

messages:
  path: /messages
  controller: App\Controller\MessageController::index

usermessages:
  path: /usermessages/{user_id}
  controller: App\Controller\MessageController::usermessages

profile:
  path: /profile
  controller: App\Controller\ProfileController::index

edit:
  path: /edit/{good_id}
  controller: App\Controller\GoodController::edit

delete:
  path: /delete/{good_id}
  controller: App\Controller\GoodController::delete

search:
  path: search/{content}_{min_price}_{max_price}_{subcategory}
  controller: App\Controller\HomeController::search

searchapi:
  path: search/{content}_{min_price}_{max_price}_{subcategory}/api
  controller: App\Controller\HomeController::searchApi